WARNING:pygls.protocol:Cancel notification for unknown message id "2"
WARNING:pygls.protocol:Cancel notification for unknown message id "69"
WARNING:pygls.protocol:Cancel notification for unknown message id "701"
Exception in thread Thread-573:
Traceback (most recent call last):
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 289, in lsp_python_diagnostic
    compile(source, uri, "exec", PyCF_ONLY_AST)
  File "file:///home/pyturtle_/Documents/ESHOPPING/ecommerce/store/admin.py", line 3
    @admin.register
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 61, in run
    return func(*args, **kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 651, in _publish_diagnostics
    diagnostic = jedi_utils.lsp_python_diagnostic(uri, doc.source)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 310, in lsp_python_diagnostic
    end=Position(line=until_line, character=until_column),
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/lsprotocol/validators.py", line 45, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
Exception in thread Thread-582:
Traceback (most recent call last):
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 289, in lsp_python_diagnostic
    compile(source, uri, "exec", PyCF_ONLY_AST)
  File "file:///home/pyturtle_/Documents/ESHOPPING/ecommerce/store/admin.py", line 3
    @admin.register(Category)
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 61, in run
    return func(*args, **kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 651, in _publish_diagnostics
    diagnostic = jedi_utils.lsp_python_diagnostic(uri, doc.source)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 310, in lsp_python_diagnostic
    end=Position(line=until_line, character=until_column),
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/lsprotocol/validators.py", line 45, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
Exception in thread Thread-733:
Traceback (most recent call last):
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 289, in lsp_python_diagnostic
    compile(source, uri, "exec", PyCF_ONLY_AST)
  File "file:///home/pyturtle_/Documents/ESHOPPING/ecommerce/store/admin.py", line 8
    @admin.register
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 61, in run
    return func(*args, **kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 651, in _publish_diagnostics
    diagnostic = jedi_utils.lsp_python_diagnostic(uri, doc.source)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 310, in lsp_python_diagnostic
    end=Position(line=until_line, character=until_column),
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/lsprotocol/validators.py", line 45, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
Exception in thread Thread-741:
Traceback (most recent call last):
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 289, in lsp_python_diagnostic
    compile(source, uri, "exec", PyCF_ONLY_AST)
  File "file:///home/pyturtle_/Documents/ESHOPPING/ecommerce/store/admin.py", line 8
    @admin.register(Product)
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 61, in run
    return func(*args, **kwargs)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 651, in _publish_diagnostics
    diagnostic = jedi_utils.lsp_python_diagnostic(uri, doc.source)
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/jedi_language_server/jedi_utils.py", line 310, in lsp_python_diagnostic
    end=Position(line=until_line, character=until_column),
  File "<attrs generated init lsprotocol.types.Position>", line 7, in __init__
  File "/home/pyturtle_/.vscode-oss/extensions/ms-python.python-2023.6.1-universal/pythonFiles/lib/jedilsp/lsprotocol/validators.py", line 45, in uinteger_validator
    raise ValueError(
ValueError: Position.character should be in range [0:2147483647], but was -1.
